CREATE TABLE mapping_metric_history
(
    history_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    source_platform VARCHAR(255)                            NOT NULL,
    platform_id     VARCHAR(255)                            NOT NULL,
    raw_score       DOUBLE PRECISION,
    raw_popularity  DOUBLE PRECISION,
    recorded_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_mapping_metric_history PRIMARY KEY (history_id)
);

-- 支持按平台条目查询按时间倒序排列的历史记录。
CREATE INDEX idx_mapping_metric_history_series
    ON mapping_metric_history (source_platform, platform_id, recorded_at DESC);

-- 将现有 Mapping 的当前状态作为历史起点。
INSERT INTO mapping_metric_history (source_platform, platform_id, raw_score, raw_popularity, recorded_at)
SELECT source_platform,
       platform_id,
       raw_score,
       raw_popularity,
       update_time
FROM mapping;
